apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vpcpostgresqlinstances.aws.database.example.org
  labels:
    provider: aws
    guide: quickstart
    vpc: new
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XPostgreSQLInstance
  resources:
    - name: vpc
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            region: eu-west-1
            cidrBlock: 192.168.0.0/16
            enableDnsSupport: true
            enableDnsHostNames: true
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
    - name: subnet-a
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: eu-west-1a
        spec:
          forProvider:
            region: eu-west-1
            cidrBlock: 192.168.64.0/18
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: eu-west-1a
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "metadata.labels[zone]"
          transforms:
            - type: string
              string:
                fmt: "%sa"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.availabilityZone"
          transforms:
            - type: string
              string:
                fmt: "%sa"
    - name: subnet-b
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: eu-west-1b
        spec:
          forProvider:
            region: eu-west-1
            cidrBlock: 192.168.128.0/18
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: eu-west-1b
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "metadata.labels[zone]"
          transforms:
            - type: string
              string:
                fmt: "%sb"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.availabilityZone"
          transforms:
            - type: string
              string:
                fmt: "%sb"
    - name: subnet-c
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: eu-west-1c
        spec:
          forProvider:
            region: eu-west-1
            cidrBlock: 192.168.192.0/18
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: eu-west-1c
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "metadata.labels[zone]"
          transforms:
            - type: string
              string:
                fmt: "%sc"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.availabilityZone"
          transforms:
            - type: string
              string:
                fmt: "%sc"
    - name: dbsubnetgroup
      base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: DBSubnetGroup
        spec:
          forProvider:
            region: eu-west-1
            description: An excellent formation of subnetworks.
            subnetIdSelector:
              matchControllerRef: true
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
    - name: internetgateway
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: InternetGateway
        spec:
          forProvider:
            region: eu-west-1
            vpcIdSelector:
              matchControllerRef: true
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
    - name: routetable
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            region: eu-west-1
            vpcIdSelector:
              matchControllerRef: true
            routes:
              - destinationCidrBlock: 0.0.0.0/0
                gatewayIdSelector:
                  matchControllerRef: true
            associations:
              - subnetIdSelector:
                  matchLabels:
                    zone: eu-west-1a
              - subnetIdSelector:
                  matchLabels:
                    zone: eu-west-1b
              - subnetIdSelector:
                  matchLabels:
                    zone: eu-west-1c
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.associations[0].subnetIdSelector.matchLabels[zone]"
          transforms:
            - type: string
              string:
                fmt: "%sa"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.associations[1].subnetIdSelector.matchLabels[zone]"          
          transforms:
            - type: string
              string:
                fmt: "%sb"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.associations[2].subnetIdSelector.matchLabels[zone]"
          transforms:
            - type: string
              string:
                fmt: "%sc"
    - name: securitygroup
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: SecurityGroup
        spec:
          forProvider:
            region: eu-west-1
            vpcIdSelector:
              matchControllerRef: true
            groupName: crossplane-getting-started
            description: Allow access to PostgreSQL
            ingress:
              - fromPort: 5432
                toPort: 5432
                ipProtocol: tcp
                ipRanges:
                  - cidrIp: 0.0.0.0/0
                    description: Everywhere
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
    - name: rdsinstance
      base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: RDSInstance
        spec:
          forProvider:
            region: eu-west-1
            dbSubnetGroupNameSelector:
              matchControllerRef: true
            vpcSecurityGroupIDSelector:
              matchControllerRef: true
            dbInstanceClass: db.t2.small
            masterUsername: masteruser
            engine: postgres
            engineVersion: "12"
            skipFinalSnapshotBeforeDeletion: true
            publiclyAccessible: true
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
        - fromFieldPath: "spec.parameters.storageGB"
          toFieldPath: "spec.forProvider.allocatedStorage"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port
